name: Deploy Nginx

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Nginx on Remote Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull nginx
            docker stop nginx-container || true
            docker rm nginx-container || true
            docker run -d --name nginx-container -p 80:80 nginx
